#messaggi
#Per colorare i messaggi utilizare &
messaggio_pre_partita: "Il gioco inizierà tra %secs%!"
messaggio_non_abbastanza_player: "Non ci sono abbastanza giocatori per iniziare la partita!"
messaggio_avviso_in_partita: "Verrai tippato tra %secs%!"
messaggio_vittoria: "Hai vinto!"