name: ${project.artifactId}
version: ${project.version}
main: ${project.groupId}.aresondeathswap.${project.artifactId}
api-version: "1.16"
author: Areson
depend: [ PlaceholderAPI, Multiverse-Core ]

commands:
  play:
    usage: "/play"
  leave:
    usage: "/leave"
  spawn:
    usage: "/spawn"
  setArena:
    usage: "/setArena"
    permission: aresonDeathSwap.admin
  deleteArena:
    usage: "/deleteArena"
    permission: aresonDeathSwap.admin
  loadWorld:
    usage: "/loadWorld"
    permission: aresonDeathSwap.admin
  tpWorld:
    usage: "/tpWorld"
    permission: aresonDeathSwap.admin
  setspawn:
    usage: "/setSpawn"
    permission: aresonDeathSwap.admin
  testcommand:
    usage: "/testcommand"
    permission: aresonDeathSwap.admin
  forceswap:
    usage: "/forceswap"
    permission: aresonDeathSwap.admin

permissions:
  aresonDeathSwap.admin:
    default: op
