name: ${project.artifactId}
version: ${project.version}
main: ${project.groupId}.aresondeathswap.${project.artifactId}
api-version: "1.16"
author: Areson
depend: [ PlaceholderAPI, Multiverse-Core ]

commands:
  test:
    permission: op

permissions:
  deathswap.admin:
    default: op
