name: ${project.artifactId}
version: ${project.version}
main: ${project.groupId}.aresondeathswap.${project.artifactId}
api-version: "1.16"
author: Areson


commands:
  play:
    usage: "/play"
  setArena:
    usage: "/setArena"
    permission: aresonDeathSwap.admin
  loadWorld:
    usage: "/loadWorld"
    permission: aresonDeathSwap.admin
  tpWorld:
    usage: "/tpWorld"
    permission: aresonDeathSwap.admin

permissions:
  aresonDeathSwap.admin:
    default: op