name: ${project.artifactId}
version: ${project.version}
main: ${project.groupId}.aresondeathswap.${project.artifactId}
api-version: "1.16"
author: Areson
depend:  [PlaceholderAPI]

commands:
  play:
    usage: "/play"
  leave:
    usage: "/leave"
  arenaReady:
    usage: "/arenaReady"
    permission: aresonDeathSwap.admin
  deleteArena:
    usage: "/deleteArena"
    permission: aresonDeathSwap.admin
  loadWorld:
    usage: "/loadWorld"
    permission: aresonDeathSwap.admin
  tpWorld:
    usage: "/tpWorld"
    permission: aresonDeathSwap.admin
  setSpawnPoint:
    usage: "/setSpawnPoint"
    permission: aresonDeathSwap.admin

permissions:
  aresonDeathSwap.admin:
    default: op
