name: ${project.artifactId}
version: ${project.version}
main: ${project.groupId}.aresondeathswap.${project.artifactId}
api-version: "1.16"
author: Areson
depend: [ PlaceholderAPI, Multiverse-Core ]

commands:
  arena:
    permission: deathswap.admin
  situation:
    permission: deathswap.admin
  play:
    permission: deathswap.play
  leave:
    permission: deathswap.play

permissions:
  deathswap.admin:
    default: op
  deathswap.play:
    default: true
